config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :collections
  resources :items
  root 'collections#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :items
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :collection
  belongs_to :status
  validates :name, presence: true
  validates :notes, length: { maximum: 100,
    too_long: "Notes can only be up to 100 characters" }
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :collections
  validates :username, presence: true
  validates :username, length: { maximum: 16,
    too_long: "username must be between 4 and 16 characters" }
  validates :username, length: { minimum: 4,
    too_short: "username must be between 4 and 16 characters" }
  validates :username, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:update, keys: [:email, :password])
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @item = Item.new
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection }
        format.json { render :show, status: :ok, location: @collection }
        # format.js
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
        # format.js
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :public, :user_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy, :show]
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item.collection, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        @collection = @item.collection
        format.html { render 'collections/show' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item.collection, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
        format.js { render 'show' }
      else
        format.html { render 'collections/show' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
        format.js { render 'show' }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @item.collection, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def edit
    @collection = @item.collection
  end

private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :status_id, :collection_id, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/collections/_form.html.erb
<%= form_with(model: collection, local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :collection_name %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public, id: :collection_public %>
  </div>

  <div class="field">
    <input type="hidden" name="collection[user_id]" value="<%= current_user.id %>">
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Public</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= collection.public %></td>
        <td><%= collection.user.username %></td>
        <td><%= link_to 'View collection', collection %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <%= @collection.name %>
</h3>

<p>
  <strong>Public:</strong>
  <%= @collection.public %>
</br>
  <strong>User:</strong>
  <%= @collection.user.username %>
</p>

<!-- might need to add format.js here but currently that renders update.js.erb instead of executing it -->
<%= form_with(model: @collection, remote: true, class: :collection_update) do |form| %>
  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public, id: :collection_public %>
  </div>

<%end%>

<%= link_to 'Edit collection', edit_collection_path(@collection) %> |
<%= link_to 'Destroy collection', @collection, method: :delete, data: { confirm: 'Are you sure?' } %> <br />
  <div class="new_product_hidden new_product_field">
    <strong>New product</strong>
    <%= render 'items/form', item: @item %>
  </div>
  <button class="btn-primary new_product_button hidden_field">Add product</button>
<p>
  <h3>Products:</h3>
</p>
<div class="list-group">
  <% @collection.items.each do |item| %>
    <div class="list-group-item" id="item<%=item.id%>">
      <%=render item%>
      <!-- rails knows that "item" is the _item partial in the items view folder -->
    </div>
  <% end %>
</div>
<%= link_to 'Back', collections_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, remote: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name, maxlength: 50, size: 60 %>
  </div>

  <div class="field">
    <input type="hidden" name="item[collection_id]" value="<%= @collection.id %>">
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.collection_select(:status_id, Status.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes, maxlength: 100, size: 120 %>
  </div>

  <div class="actions">
    <%= form.submit "Save"%>
  </div>

  <%if action_name=="edit"%>
    <%= link_to 'Close', item_path(@item), remote: true %>
  <%end%>
<% end %>

app/views/items/_item.html.erb
  <strong><%= item.name %></strong>
  <p>Status: <%= item.status.name %> </p>
  <% if !(item.notes.nil?) %>
    <p>Notes: <%= item.notes %></p>
  <% end %>
  <%= link_to 'Remove', item, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
  <%= link_to 'Edit', edit_item_path(item), remote: true %>
  <div id="itemEdit<%=item.id%>">
  </div>

app/views/items/destroy.js.erb
$('#item<%=@item.id%>').remove();

app/views/items/edit.js.erb
$('#item<%=@item.id%>').html("<%= j render 'form', item: @item %>")

app/views/items/show.js.erb
$('#item<%=@item.id%>').html('<%= j render @item %>')

app/views/items/update.js.erb
$('#item<%=@item.id%>').html('<%= j render @item %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <p class="alert"><%= alert %></p>
      <% unless devise_controller? %>
        <% if user_signed_in? %>
          <li>
            <%= link_to('Log out', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li>
            <%= link_to('Log in', new_user_session_path)  %>
          </li>
          <li>
            <%= link_to('Sign up', '/users/sign_up') %>
          </li>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>